import Head from "next/head";
import { About, HomePage, Team, Projects } from "../containers";

export default function Home() {
  return (
    <>
      <Head>
        <title>CodeIndex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <HomePage />
        <About />
        <Team />
        <Projects />
      </main>
    </>
  );
}
